# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekhue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='artist',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='painting',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='painting',
            name='title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
