# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekhue', '0003_painting_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
